<?php

namespace AppBundle\Repository;

/**
 * DriveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParentItems()
    {
        $em = $this->getEntityManager();
        // $query  = $em->createQuery("SELECT partial d.{id, icon, title, dateCreated, linkDetails, star, deleted, hasChildren, children}
        //                         FROM AppBundle:Drive d 
        //                         WHERE d.parent=1");
        // $parentItems = $query->getArrayResult();
        // return $parentItems;
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('d')
                     ->from('AppBundle:Drive', 'd')
                     ->where('d.parent=1');
        $parentItems = $queryBuilder->getQuery();
        return $parentItems->getArrayResult();
    }

    public function getItem($itemId)
    {
        $em = $this->getEntityManager();
        
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('d')
                     ->from('AppBundle:Drive', 'd')
                     ->where('d.id= :itemId')
                     ->setParameters(array('itemId'=>$itemId));
        $item = $queryBuilder->getQuery();
        return $item->getArrayResult();
    }

    public function getFileDirectory(&$parentItems)
    {
        $parents = array();
        foreach ($parentItems as $key => $value)
        {
            $children = array();
            if ($parentItems[$key]['hasChildren']===true) {
                foreach ($parentItems[$key]['children'] as $child) {
                    $parents = $this->getItem($child);
                    \array_push($children, $parents[0]);                    
                }
                $parentItems[$key]['children'] = $children;
                $this->getFileDirectory($parentItems[$key]['children']);
            }
        }
        return $parentItems;
    }
}
